layout_spectrum: 0.7744569
typography_spectrum: 0.005937722
color:
  saturation: 0.899425
  lightness: 0.004304727
  brandStrength: 0.0529671
  rhythmicContrast: 0.1328679
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Test Me Baby
